-- Run this in Supabase Dashboard -> SQL Editor (after 0000..0009).
-- Safe to re-run: every step is idempotent.
--
-- ============================================================
-- เปลี่ยนรูปแบบการจอง: จากเลือกเวลาเอง -> เลือกช่วงที่แอดมินเปิดไว้
-- ============================================================
-- 0009 ให้ผู้ใช้ส่ง start_time / end_time อะไรก็ได้ที่อยู่ในเวลาเปิด-ปิดของ
-- venue แล้ว generate ช่องละ 1 ชม. ให้อัตโนมัติ
--
-- แต่ระบบจริงคือ "แอดมินเป็นคนลงว่าวันนี้เปิดให้จองช่วงไหนบ้าง" ซึ่งต่างกัน
-- สองเรื่อง:
--   1. แต่ละวันเปิดไม่เหมือนกันได้ (วันหยุด, วันปิดซ่อม, จัดแข่งครึ่งวัน)
--   2. ช่วงเวลาไม่จำเป็นต้องยาวเท่ากันหรือต่อกันสนิท (เว้นพักกลางวันได้)
-- ทั้งสองเรื่องนี้ generate จากเวลาเปิด-ปิดไม่ได้ ต้องมีตารางเก็บจริง
--
-- ผลพลอยได้ด้านความปลอดภัย: เมื่อ client ส่งได้แค่ "id ของช่วงเวลา"
-- เวลาเริ่ม-จบก็ไม่มีทางถูกกำหนดจากฝั่งผู้ใช้อีกเลย (ดูต่อใน 0011)


-- ============================================================
-- 1. ตารางช่วงเวลาที่เปิดให้จอง
-- ============================================================

create table if not exists public.facility_time_slots (

    id bigint generated by default as identity primary key,

    facility_id bigint not null
        references public.facilities(id)
        on delete cascade,

    slot_date date not null,

    start_time time not null,

    end_time time not null,

    -- ปิดช่วงเวลาชั่วคราวโดยไม่ลบทิ้ง (การจองเดิมที่ผูกอยู่จะได้ไม่หายไปด้วย)
    is_active boolean not null default true,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    constraint facility_time_slots_time_check
        check (end_time > start_time),

    constraint facility_time_slots_unique
        unique (facility_id, slot_date, start_time)

);


-- ============================================================
-- 2. กันแอดมินลงช่วงเวลาทับกันเอง
-- ============================================================
-- unique (facility_id, slot_date, start_time) กันได้แค่ "เริ่มเวลาเดียวกัน"
-- แต่ 09:00-11:00 กับ 10:00-12:00 เริ่มคนละเวลา ผ่าน unique ไปได้สบาย
-- แล้วผู้ใช้สองคนจะจองสองช่วงนี้พร้อมกันไม่ได้ (ชนกันที่ bookings) —
-- กลายเป็นช่วงเวลาที่โชว์ว่าว่างแต่จองไม่ได้จริง
--
-- ใช้วิธีเดียวกับ bookings_no_overlap ใน 0000: generated tsrange + gist

alter table public.facility_time_slots
add column if not exists slot_span tsrange
generated always as (
    tsrange(
        (slot_date + start_time)::timestamp,
        (slot_date + end_time)::timestamp,
        '[)'
    )
) stored;


alter table public.facility_time_slots
drop constraint if exists facility_time_slots_no_overlap;


alter table public.facility_time_slots
add constraint facility_time_slots_no_overlap
exclude using gist (
    facility_id with =,
    slot_span with &&
);


create index if not exists idx_facility_time_slots_lookup
on public.facility_time_slots (facility_id, slot_date);


drop trigger if exists trg_facility_time_slots_updated_at
on public.facility_time_slots;

create trigger trg_facility_time_slots_updated_at
before update on public.facility_time_slots
for each row
execute function public.set_updated_at();


-- ============================================================
-- 3. RLS
-- ============================================================

alter table public.facility_time_slots enable row level security;


drop policy if exists "facility_time_slots_public_read" on public.facility_time_slots;

create policy "facility_time_slots_public_read"
on public.facility_time_slots
for select
to anon, authenticated
using (
    is_active = true
    or public.is_admin()
);


drop policy if exists "facility_time_slots_admin_manage" on public.facility_time_slots;

create policy "facility_time_slots_admin_manage"
on public.facility_time_slots
for all
to authenticated
using (
    public.is_admin()
)
with check (
    public.is_admin()
);


-- ============================================================
-- 4. ตัวช่วยสร้างช่วงเวลาทีละหลายวัน
-- ============================================================
-- ตารางเป็นรายวันตามที่ต้องการ แต่การคีย์มือ 15 สนาม x 60 วัน = ~900 แถว
-- ไม่ใช่งานที่คนควรทำ ฟังก์ชันนี้คือปุ่ม "เปิดจองล่วงหน้า 1 เดือน" ของหน้า
-- Admin — สร้างแบบสม่ำเสมอให้ก่อน แล้วแอดมินค่อยเข้าไปลบ/แก้เป็นวัน ๆ
--
-- ตั้งใจให้เป็น SECURITY INVOKER (ค่าเริ่มต้น) ไม่ใช่ DEFINER:
-- สิทธิ์การเขียนจึงถูกตัดสินโดย facility_time_slots_admin_manage ตามปกติ
-- ไม่ต้องเช็ค is_admin() ซ้ำในตัวฟังก์ชัน และไม่มีทางลืมเช็ค
--
-- คืนจำนวนแถวที่สร้างจริง — ช่วงที่ทับของเดิมจะถูกข้าม ไม่ใช่ error
-- ทำให้กดซ้ำเพื่อ "ต่ออายุอีกเดือน" ได้โดยไม่ต้องกลัวพัง

create or replace function public.generate_facility_slots(
  p_facility_id   bigint,
  p_from          date,
  p_to            date,
  p_start_time    time,
  p_end_time      time,
  p_slot_minutes  integer default 60
)
returns integer
language plpgsql
set search_path = public
as $fn$
declare
  v_inserted integer;
begin
  if p_slot_minutes <= 0 then
    raise exception 'ความยาวช่วงเวลาต้องมากกว่า 0 นาที';
  end if;

  if p_end_time <= p_start_time then
    raise exception 'เวลาสิ้นสุดต้องอยู่หลังเวลาเริ่ม';
  end if;

  if p_to < p_from then
    raise exception 'วันสิ้นสุดต้องไม่อยู่ก่อนวันเริ่ม';
  end if;

  if p_to - p_from > 365 then
    raise exception 'สร้างล่วงหน้าได้ไม่เกิน 365 วันต่อครั้ง';
  end if;

  with candidate as (
    select
      d::date                                              as slot_date,
      g::time                                              as start_time,
      (g + make_interval(mins => p_slot_minutes))::time    as end_time
    from generate_series(p_from, p_to, interval '1 day') as d
    cross join lateral generate_series(
      d::date + p_start_time,
      -- ตัดเศษท้ายทิ้ง: เปิด 08:00-23:00 ช่วงละ 2 ชม. ได้ถึง 20:00-22:00
      -- ไม่สร้าง 22:00-24:00 ที่ล้นเวลาปิด
      d::date + p_end_time - make_interval(mins => p_slot_minutes),
      make_interval(mins => p_slot_minutes)
    ) as g
  )
  insert into public.facility_time_slots (facility_id, slot_date, start_time, end_time)
  select p_facility_id, c.slot_date, c.start_time, c.end_time
  from candidate c
  where not exists (
    -- ข้ามช่วงที่ทับของเดิม ไม่ใช่ปล่อยให้ exclusion constraint โยน error
    -- ทั้งชุด เพราะแอดมินอาจเคยลงช่วงพิเศษของบางวันไว้แล้ว
    select 1
    from public.facility_time_slots x
    where x.facility_id = p_facility_id
      and x.slot_date   = c.slot_date
      and x.start_time  < c.end_time
      and x.end_time    > c.start_time
  );

  get diagnostics v_inserted = row_count;

  return v_inserted;
end;
$fn$;


revoke all on function
  public.generate_facility_slots(bigint, date, date, time, time, integer)
from public, anon;

grant execute on function
  public.generate_facility_slots(bigint, date, date, time, time, integer)
to authenticated;


-- ============================================================
-- 5. เปิดจองล่วงหน้า 60 วันให้สนามที่ seed ไว้ใน 0008
-- ============================================================
-- ความยาวช่วงแยกตามชนิดกีฬา: คอร์ตแบด/เทนนิสเช่ากันเป็นชั่วโมง
-- ส่วนสนามทีมมักเล่นกันรอบละ 2 ชม.
--
-- ข้อควรรู้: ช่วงเวลาหมดอายุไปตามวัน พอเลย 60 วันแล้วจะไม่มีอะไรให้จอง
-- จนกว่าแอดมินจะกดสร้างเพิ่ม — เป็นธรรมชาติของตารางรายวัน ไม่ใช่บั๊ก

do $$
declare
  r record;
begin
  for r in
    select
      f.id,
      v.opening_time,
      v.closing_time,
      case when s.name in ('แบดมินตัน', 'เทนนิส') then 60 else 120 end as slot_minutes
    from public.facilities f
    join public.venues v on v.id = f.venue_id
    join public.sports s on s.id = f.sport_id
    where f.status = 'available'
      and v.status = 'active'
  loop
    perform public.generate_facility_slots(
      r.id,
      current_date,
      current_date + 60,
      r.opening_time,
      r.closing_time,
      r.slot_minutes
    );
  end loop;
end;
$$;
