-- Run this in Supabase Dashboard -> SQL Editor (after 0000..0019).
-- Safe to re-run: every step is idempotent.
--
-- ============================================================
-- ต่อหน้า Admin/จัดการสิ่งอำนวยความสะดวก + หน้า Facilities สาธารณะ เข้ากับ
-- ตารางจริง (ปัจจุบันทั้งสองหน้าฮาร์ดโค้ดเนื้อหาไว้ในโค้ด ไม่มีตารางรองรับเลย)
-- ============================================================
-- ตั้งชื่อ club_amenities แยกจาก facilities (0000) ให้ชัดเจน — facilities คือ
-- สนามที่จองได้ (มี venue_id/sport_id/price_per_hour) คนละแนวคิดกับ amenities
-- ของคลับ (บาร์ ห้องอาหาร ที่จอดรถ ฯลฯ) ที่จองไม่ได้ แค่แสดงบนหน้าเว็บ
--
-- ยังคง STATS (120+ สนามพันธมิตร ฯลฯ) และส่วนผู้ก่อตั้งไว้ฮาร์ดโค้ดในหน้า
-- Facilities.jsx เหมือนเดิม — ไม่ใช่สิ่งที่หน้า admin นี้จัดการ


-- ============================================================
-- 1. ส่วนหัวของหน้า Facilities (แถวเดียว)
-- ============================================================

create table if not exists public.facilities_page_settings (

    id smallint primary key default 1,

    eyebrow text not null default '',

    heading text not null default '',

    intro text not null default '',

    updated_at timestamptz not null default now(),

    constraint facilities_page_settings_singleton check (id = 1)

);

drop trigger if exists trg_facilities_page_settings_updated_at
on public.facilities_page_settings;

create trigger trg_facilities_page_settings_updated_at
before update on public.facilities_page_settings
for each row
execute function public.set_updated_at();

-- seed ด้วยข้อความเดิมที่ฮาร์ดโค้ดอยู่ในหน้าเว็บตอนนี้ ไม่ให้หน้าว่างเปล่า
-- ทันทีที่ migration รัน
insert into public.facilities_page_settings (id, eyebrow, heading, intro)
values (
    1,
    'THE CLUB',
    'สิ่งอำนวยความสะดวก',
    'มากกว่าแค่สนามกีฬา — สปอร์ตคลับของเรามีบาร์ ห้องอาหาร และบริการครบครัน เพื่อให้ทุกการมาเยือนสมบูรณ์แบบ'
)
on conflict (id) do nothing;


-- ============================================================
-- 2. รายการสิ่งอำนวยความสะดวก
-- ============================================================

create table if not exists public.club_amenities (

    id bigint generated by default as identity primary key,

    name varchar(200) not null,

    category varchar(100) not null default '',

    description text not null default '',

    image_url text,

    position integer not null default 0,

    is_visible boolean not null default true,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    constraint club_amenities_unique_name unique (name),

    constraint club_amenities_position_check check (position >= 0)

);

create index if not exists idx_club_amenities_position
on public.club_amenities(position);

drop trigger if exists trg_club_amenities_updated_at
on public.club_amenities;

create trigger trg_club_amenities_updated_at
before update on public.club_amenities
for each row
execute function public.set_updated_at();


-- ============================================================
-- 3. ข้อมูลรายละเอียดแบบ label/value ของแต่ละรายการ (เพิ่ม/ลบได้จาก edit panel)
-- ============================================================

create table if not exists public.club_amenity_facts (

    id bigint generated by default as identity primary key,

    amenity_id bigint not null
        references public.club_amenities(id)
        on delete cascade,

    label varchar(100) not null,

    value varchar(200) not null,

    position integer not null default 0,

    constraint club_amenity_facts_unique_label unique (amenity_id, label)

);

create index if not exists idx_club_amenity_facts_amenity
on public.club_amenity_facts(amenity_id);


-- ============================================================
-- 4. seed 5 รายการเดิมที่เคยฮาร์ดโค้ดไว้ในหน้าเว็บ
-- ============================================================

insert into public.club_amenities (name, category, description, position, is_visible)
values
    (
        'SIDESTBAR',
        'บาร์ & เครื่องดื่ม',
        'มินิบาร์บรรยากาศอบอุ่นภายในสปอร์ตคลับ แสงไฟสลัวและที่นั่งเคาน์เตอร์ยาว เหมาะสำหรับนั่งพักหลังเล่นกีฬา หรือสังสรรค์กับทีมหลังจบเกม',
        0,
        true
    ),
    (
        'OMAKASE',
        'ห้องอาหาร',
        'ร้านอาหารซิกเนเจอร์ของสปอร์ตคลับ นำเข้าวัตถุดิบสดจากญี่ปุ่นทุกวัน เสิร์ฟแบบโอมากาเสะโดยเชฟประจำร้าน ที่นั่งเคาน์เตอร์ 12 ที่ ควรจองล่วงหน้า',
        1,
        true
    ),
    (
        'ห้องอาบน้ำ',
        'สิ่งอำนวยความสะดวก',
        'ห้องอาบน้ำสะอาด พร้อมล็อกเกอร์เก็บของส่วนตัว ให้บริการตลอดเวลาทำการ',
        2,
        true
    ),
    (
        'ที่จอดรถ',
        'สิ่งอำนวยความสะดวก',
        'ที่จอดรถกว้างขวาง รองรับได้ 200 คัน ฟรีสำหรับผู้จองสนาม',
        3,
        true
    ),
    (
        'Wi-Fi',
        'สิ่งอำนวยความสะดวก',
        'อินเทอร์เน็ตไร้สายความเร็วสูง ครอบคลุมทั่วบริเวณสนาม ฟรีสำหรับผู้มาใช้บริการ',
        4,
        false
    )
on conflict (name) do nothing;

insert into public.club_amenity_facts (amenity_id, label, value, position)
select a.id, f.label, f.value, f.position
from public.club_amenities a
join (
    values
        ('SIDESTBAR', 'ตำแหน่ง', 'โซนชั้นในของที่พัก', 0),
        ('SIDESTBAR', 'เมนูซิกเนเจอร์', 'Cocktail White Whiskey', 1),
        ('SIDESTBAR', 'เวลาเปิด', '17:00 – 24:00 น.', 2),
        ('OMAKASE', 'ตำแหน่ง', 'โซนชั้นในของห้องอาหาร', 0),
        ('OMAKASE', 'เมนูซิกเนเจอร์', 'Otoro Roll, Uni Sauce', 1),
        ('OMAKASE', 'เวลาเปิด', '11:00 – 22:00 น.', 2),
        ('ห้องอาบน้ำ', 'ตำแหน่ง', 'ชั้น 1', 0),
        ('ห้องอาบน้ำ', 'รายละเอียด', 'พร้อมล็อกเกอร์', 1),
        ('ที่จอดรถ', 'ความจุ', '200 คัน', 0),
        ('ที่จอดรถ', 'ค่าบริการ', 'ฟรีสำหรับผู้จอง', 1),
        ('Wi-Fi', 'ความครอบคลุม', 'ทั่วบริเวณ', 0)
) as f(amenity_name, label, value, position)
    on f.amenity_name = a.name
on conflict (amenity_id, label) do nothing;


-- ============================================================
-- 5. RLS
-- ============================================================

alter table public.facilities_page_settings enable row level security;
alter table public.club_amenities enable row level security;
alter table public.club_amenity_facts enable row level security;

-- ส่วนหัวหน้าเป็นแค่ข้อความ ไม่มี flag ซ่อน — อ่านได้เสมอ แก้ได้เฉพาะ admin
drop policy if exists "facilities_page_settings_public_read" on public.facilities_page_settings;
create policy "facilities_page_settings_public_read"
on public.facilities_page_settings
for select
to anon, authenticated
using ( true );

drop policy if exists "facilities_page_settings_admin_manage" on public.facilities_page_settings;
create policy "facilities_page_settings_admin_manage"
on public.facilities_page_settings
for update
to authenticated
using ( public.is_admin() )
with check ( public.is_admin() );

drop policy if exists "club_amenities_public_read" on public.club_amenities;
create policy "club_amenities_public_read"
on public.club_amenities
for select
to anon, authenticated
using (
    is_visible = true
    or public.is_admin()
);

drop policy if exists "club_amenities_admin_manage" on public.club_amenities;
create policy "club_amenities_admin_manage"
on public.club_amenities
for all
to authenticated
using ( public.is_admin() )
with check ( public.is_admin() );

-- ตารางลูก facts ไม่มีคอลัมน์ is_visible ของตัวเอง — มองตามการมองเห็นของ
-- amenity แม่เสมอ (ผูก join กับ club_amenities แทนเก็บซ้ำ)
drop policy if exists "club_amenity_facts_public_read" on public.club_amenity_facts;
create policy "club_amenity_facts_public_read"
on public.club_amenity_facts
for select
to anon, authenticated
using (
    exists (
        select 1 from public.club_amenities a
        where a.id = amenity_id
        and (a.is_visible = true or public.is_admin())
    )
);

drop policy if exists "club_amenity_facts_admin_manage" on public.club_amenity_facts;
create policy "club_amenity_facts_admin_manage"
on public.club_amenity_facts
for all
to authenticated
using ( public.is_admin() )
with check ( public.is_admin() );


-- ============================================================
-- 6. Storage bucket สำหรับรูปสิ่งอำนวยความสะดวก
-- ============================================================

insert into storage.buckets (id, name, public)
values ('amenities', 'amenities', true)
on conflict (id) do nothing;

drop policy if exists "Amenity images are publicly accessible" on storage.objects;
create policy "Amenity images are publicly accessible"
on storage.objects for select
using ( bucket_id = 'amenities' );

drop policy if exists "Admins can upload amenity images" on storage.objects;
create policy "Admins can upload amenity images"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'amenities'
  and public.is_admin()
);

drop policy if exists "Admins can update amenity images" on storage.objects;
create policy "Admins can update amenity images"
on storage.objects for update
to authenticated
using (
  bucket_id = 'amenities'
  and public.is_admin()
);

drop policy if exists "Admins can delete amenity images" on storage.objects;
create policy "Admins can delete amenity images"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'amenities'
  and public.is_admin()
);
