-- Run this in Supabase Dashboard -> SQL Editor (after 0000..0054).
-- Safe to re-run: every step is idempotent.
--
-- ระบบจัดส่งของรางวัล + ประวัติการแลกฝั่งแอดมิน + สิทธิ์จองล่วงหน้า
--
-- 0047 ทำฝั่ง "แลกได้" ครบแล้ว แต่ฝั่งหลังการแลกยังขาดสามอย่าง:
--
--   1) การจัดส่งมีแค่ 4 สถานะและกระโดดจาก "กำลังจัดส่ง" ไป "จัดส่งแล้ว"
--      ทีเดียว ลูกค้าไม่มีทางรู้ว่าของอยู่ตรงไหน และไม่มีที่ให้กด "ได้รับของ
--      แล้ว" เลย — ระบบถือว่าของถึงมือทันทีที่แอดมินกดส่ง ซึ่งไม่จริง
--   2) แอดมินดูได้แค่ "คิวที่ต้องจัดส่ง" (admin_reward_requests กรอง
--      fulfillment_status is not null ทิ้ง) คูปองส่วนลดที่ไม่ต้องส่งของจึง
--      หายไปจากสายตาแอดมินทั้งหมด ไม่มีหน้าไหนตอบได้ว่าใครแลกอะไรไปบ้าง
--   3) รางวัล "สิทธิ์จองล่วงหน้า 30 วัน" ที่ seed ไว้เป็น benefit_type='none'
--      คือแลกแล้วไม่มีผลกับระบบเลย ซ้ำร้ายกว่านั้นคือทุกคนจองล่วงหน้าได้ 62 วัน
--      อยู่แล้ว สิทธิ์ที่ขาย 3,000 แต้มจึงให้น้อยกว่าที่ทุกคนมีฟรี


-- ============================================================
-- 1. ข้อมูลการจัดส่งที่ละเอียดขึ้น
-- ============================================================
-- carrier/note แยกจาก tracking_number เพราะเลขพัสดุอย่างเดียวใช้ตามของไม่ได้
-- ถ้าไม่รู้ว่าเป็นของขนส่งเจ้าไหน (เลขของ Kerry กับ Flash หน้าตาใกล้กันมาก)

alter table public.reward_redemptions
  add column if not exists shipping_carrier text,
  add column if not exists shipping_note    text,
  add column if not exists delivered_at     timestamptz,
  add column if not exists received_at      timestamptz;

-- 'shipping' ของเดิมกำกวม (ส่งแล้ว? หรือกำลังไปถึง?) — ย้ายไปเป็น 'in_transit'
-- ที่มีความหมายเดียว หน้าเว็บยังแมป 'shipping' ไว้เผื่อแถวที่หลุดรอดมา
update public.reward_redemptions
set fulfillment_status = 'in_transit'
where fulfillment_status = 'shipping';


-- ============================================================
-- 2. ไทม์ไลน์การจัดส่ง
-- ============================================================
-- เก็บทุกครั้งที่สถานะขยับเป็นแถวใหม่ ไม่ใช่ทับค่าเดิม — ลูกค้าต้องเห็นว่า
-- "เตรียมของวันที่ 1 ส่งวันที่ 2 ถึงวันที่ 4" ไม่ใช่เห็นแค่สถานะล่าสุดลอย ๆ
-- และเวลามีปัญหา (ของตีกลับ ส่งซ้ำ) จะมีหลักฐานว่าเกิดอะไรขึ้นตามลำดับ

create table if not exists public.reward_shipment_events (
  id              bigint generated by default as identity primary key,
  redemption_id   uuid not null references public.reward_redemptions(id) on delete cascade,
  status          public.reward_fulfillment_status not null,
  note            text,
  tracking_number text,
  carrier         text,
  created_by      uuid references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now()
);

create index if not exists idx_shipment_events_redemption
on public.reward_shipment_events(redemption_id, created_at);

alter table public.reward_shipment_events enable row level security;

-- อ่านได้เฉพาะเจ้าของคูปองกับแอดมิน และไม่มี policy insert/update/delete เลย
-- โดยตั้งใจ — ทุกแถวเกิดจาก RPC security definer ข้างล่างเท่านั้น ลูกค้าจึง
-- ปลอมไทม์ไลน์ว่า "ส่งแล้ว" เองไม่ได้
drop policy if exists "shipment_events_read" on public.reward_shipment_events;
create policy "shipment_events_read"
on public.reward_shipment_events
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1 from public.reward_redemptions rr
    where rr.id = redemption_id
      and rr.user_id = (select auth.uid())
  )
);

revoke all on public.reward_shipment_events from anon, authenticated;
grant select on public.reward_shipment_events to authenticated;


-- ============================================================
-- 3. ลำดับขั้นของสถานะจัดส่ง
-- ============================================================
-- ใช้ทั้งตอนตรวจว่าเดินหน้าถูกทางไหม และตอนเรียงไทม์ไลน์ — เขียนที่เดียวเพื่อ
-- ไม่ให้ฝั่ง SQL กับฝั่งหน้าเว็บนิยามลำดับไม่ตรงกัน
--
-- pickup แยกเส้นทาง (นัดรับที่สนาม ไม่มีขนส่งมาเกี่ยว) จึงให้ step เท่ากับ
-- "จัดส่งสำเร็จ" คือรอแค่ลูกค้ามารับแล้วกดยืนยัน

create or replace function public.reward_fulfillment_step(
  p_status public.reward_fulfillment_status
)
returns integer
language sql
immutable
as $$
  select case p_status
    when 'pending'    then 0
    when 'preparing'  then 1
    when 'shipped'    then 2
    when 'shipping'   then 3
    when 'in_transit' then 3
    when 'pickup'     then 4
    when 'delivered'  then 4
    when 'received'   then 5
    else 0
  end;
$$;

grant execute on function public.reward_fulfillment_step(public.reward_fulfillment_status)
  to authenticated, anon;


-- ============================================================
-- 4. อัปเดตสถานะจัดส่ง (แอดมิน)
-- ============================================================
-- signature เปลี่ยน (เพิ่ม carrier/note) จึงต้อง drop ตัวเก่าทิ้งก่อน ไม่งั้น
-- จะมีสองตัวชื่อเดียวกันแล้ว PostgREST เลือกไม่ถูก
--
-- 'received' ไม่ให้แอดมินตั้งเอง — "ลูกค้ายืนยันได้รับแล้ว" ต้องมาจากลูกค้า
-- เท่านั้น ไม่งั้นสถานะนั้นก็ไม่ได้แปลว่าอะไรเลย
--
-- ปิดคูปองเป็น completed ตอน 'delivered' (ไม่ใช่ตอน 'shipped' แบบเดิม) เพราะ
-- ของที่เพิ่งออกจากคลังยังไม่ถึงมือใคร ถ้านับว่า "ใช้แล้ว" ตั้งแต่ตอนนั้น
-- ตัวเลข "แลกแล้วยังไม่ได้ใช้" ของแอดมินจะต่ำกว่าความจริงตลอด

drop function if exists public.admin_update_redemption_fulfillment(
  uuid, public.reward_fulfillment_status, text
);

create or replace function public.admin_update_redemption_fulfillment(
  p_id       uuid,
  p_status   public.reward_fulfillment_status,
  p_tracking text default null,
  p_carrier  text default null,
  p_note     text default null
)
returns public.reward_redemptions
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_row    public.reward_redemptions;
  v_reward public.rewards;
  v_label  text;
begin
  if not public.is_admin() then
    raise exception 'ต้องเป็นผู้ดูแลระบบเท่านั้น';
  end if;

  if p_status = 'received' then
    raise exception 'สถานะ "ลูกค้ายืนยันได้รับแล้ว" ต้องให้ลูกค้าเป็นคนกดยืนยันเอง';
  end if;

  select * into v_row
  from public.reward_redemptions
  where id = p_id
  for update;

  if not found then
    raise exception 'ไม่พบคำขอแลกรางวัลนี้';
  end if;

  if v_row.status = 'cancelled' then
    raise exception 'คำขอนี้ถูกยกเลิกไปแล้ว';
  end if;

  if v_row.fulfillment_status is null then
    raise exception 'ของรางวัลนี้ไม่ต้องจัดส่ง จึงอัปเดตสถานะจัดส่งไม่ได้';
  end if;

  if v_row.fulfillment_status = 'received' then
    raise exception 'ลูกค้ายืนยันรับของแล้ว ไม่สามารถเปลี่ยนสถานะย้อนกลับได้';
  end if;

  select * into v_reward from public.rewards where id = v_row.reward_id;

  update public.reward_redemptions
  set fulfillment_status = p_status,
      tracking_number    = coalesce(nullif(btrim(coalesce(p_tracking, '')), ''), tracking_number),
      shipping_carrier   = coalesce(nullif(btrim(coalesce(p_carrier, '')), ''), shipping_carrier),
      shipping_note      = coalesce(nullif(btrim(coalesce(p_note, '')), ''), shipping_note),
      shipped_at         = case when p_status = 'shipped'   then coalesce(shipped_at, now())   else shipped_at end,
      delivered_at       = case when p_status = 'delivered' then coalesce(delivered_at, now()) else delivered_at end,
      status             = case when p_status = 'delivered' then 'completed'::public.redemption_status else status end,
      used_at            = case when p_status = 'delivered' then coalesce(used_at, now()) else used_at end
  where id = p_id
  returning * into v_row;

  insert into public.reward_shipment_events
    (redemption_id, status, note, tracking_number, carrier, created_by)
  values (
    p_id,
    p_status,
    nullif(btrim(coalesce(p_note, '')), ''),
    v_row.tracking_number,
    v_row.shipping_carrier,
    (select auth.uid())
  );

  v_label := case p_status
    when 'preparing'  then 'กำลังเตรียมสินค้า'
    when 'shipped'    then 'จัดส่งแล้ว'
    when 'in_transit' then 'อยู่ระหว่างขนส่ง'
    when 'delivered'  then 'จัดส่งสำเร็จ'
    when 'pickup'     then 'พร้อมให้รับที่สนาม'
    else 'รอดำเนินการ'
  end;

  -- ไม่แจ้งเตือนตอนถอยกลับไป 'pending' — เป็นการแก้ข้อมูลฝั่งหลังบ้าน ไม่ใช่
  -- ความคืบหน้าที่ลูกค้าต้องรู้
  if p_status <> 'pending' then
    insert into public.notifications
      (user_id, type, title, message, reference_type, reference_id)
    values (
      v_row.user_id,
      'reward_shipping',
      format('ของรางวัล: %s', v_label),
      format(
        '"%s" %s%s%s',
        v_reward.name,
        v_label,
        coalesce(' · เลขพัสดุ ' || v_row.tracking_number, ''),
        case when p_status = 'delivered'
             then ' — กรุณากดยืนยันเมื่อได้รับของแล้วที่หน้าประวัติการแลกรางวัล'
             else '' end
      ),
      'redemption',
      v_row.id::text
    );
  end if;

  return v_row;
end;
$fn$;

revoke all on function public.admin_update_redemption_fulfillment(
  uuid, public.reward_fulfillment_status, text, text, text
) from public, anon;
grant execute on function public.admin_update_redemption_fulfillment(
  uuid, public.reward_fulfillment_status, text, text, text
) to authenticated, service_role;


-- ============================================================
-- 5. ลูกค้ายืนยันว่าได้รับของรางวัลแล้ว
-- ============================================================
-- ใช้ได้ตั้งแต่ของออกจากคลังไปแล้ว (shipped ขึ้นไป) รวมถึงของที่นัดรับที่สนาม
-- — ก่อนหน้านั้นยังไม่มีอะไรให้ยืนยัน
--
-- ปิดคูปองเป็น completed ด้วยเสมอ ต่อให้แอดมินยังไม่ได้กด 'delivered' เพราะ
-- ของถึงมือลูกค้าจริงแล้วคือจุดจบของรายการนี้ ไม่ว่าสถานะฝั่งหลังบ้านจะตามทัน
-- หรือไม่

create or replace function public.confirm_redemption_received(
  p_id   uuid,
  p_note text default null
)
returns public.reward_redemptions
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_me  uuid := (select auth.uid());
  v_row public.reward_redemptions;
begin
  if v_me is null then
    raise exception 'ต้องเข้าสู่ระบบก่อน';
  end if;

  select * into v_row
  from public.reward_redemptions
  where id = p_id
  for update;

  if not found or v_row.user_id <> v_me then
    raise exception 'ไม่พบรายการแลกรางวัลนี้';
  end if;

  if v_row.status = 'cancelled' then
    raise exception 'รายการนี้ถูกยกเลิกไปแล้ว';
  end if;

  if v_row.fulfillment_status is null then
    raise exception 'ของรางวัลนี้ไม่มีการจัดส่ง จึงไม่ต้องยืนยันการรับของ';
  end if;

  if v_row.fulfillment_status = 'received' then
    return v_row;
  end if;

  if public.reward_fulfillment_step(v_row.fulfillment_status) < 2 then
    raise exception 'ของรางวัลยังไม่ถูกจัดส่ง ยังยืนยันการรับของไม่ได้';
  end if;

  update public.reward_redemptions
  set fulfillment_status = 'received',
      received_at        = coalesce(received_at, now()),
      delivered_at       = coalesce(delivered_at, now()),
      status             = 'completed',
      used_at            = coalesce(used_at, now()),
      used_note          = coalesce(used_note, nullif(btrim(coalesce(p_note, '')), ''),
                                    'ลูกค้ายืนยันว่าได้รับของรางวัลแล้ว')
  where id = p_id
  returning * into v_row;

  insert into public.reward_shipment_events
    (redemption_id, status, note, tracking_number, carrier, created_by)
  values (
    p_id,
    'received',
    coalesce(nullif(btrim(coalesce(p_note, '')), ''), 'ลูกค้ายืนยันว่าได้รับของรางวัลแล้ว'),
    v_row.tracking_number,
    v_row.shipping_carrier,
    v_me
  );

  return v_row;
end;
$fn$;

revoke all on function public.confirm_redemption_received(uuid, text) from public, anon;
grant execute on function public.confirm_redemption_received(uuid, text) to authenticated;


-- ============================================================
-- 6. สรุปคิวจัดส่ง (แอดมิน) — ตามสถานะชุดใหม่
-- ============================================================
drop function if exists public.admin_reward_fulfillment_stats();

create function public.admin_reward_fulfillment_stats()
returns table (
  pending_count   integer,
  preparing_count integer,
  shipped_count   integer,
  transit_count   integer,
  delivered_count integer,
  received_count  integer,
  pickup_count    integer,
  shipped_month   integer
)
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_month timestamp := date_trunc('month', now() at time zone 'Asia/Bangkok');
begin
  if not public.is_admin() then
    raise exception 'ต้องเป็นผู้ดูแลระบบเท่านั้น';
  end if;

  return query
  select
    count(*) filter (where rr.fulfillment_status = 'pending')::integer,
    count(*) filter (where rr.fulfillment_status = 'preparing')::integer,
    count(*) filter (where rr.fulfillment_status = 'shipped')::integer,
    count(*) filter (where rr.fulfillment_status in ('in_transit', 'shipping'))::integer,
    count(*) filter (where rr.fulfillment_status = 'delivered')::integer,
    count(*) filter (where rr.fulfillment_status = 'received')::integer,
    count(*) filter (where rr.fulfillment_status = 'pickup')::integer,
    count(*) filter (
      where rr.shipped_at is not null
        and date_trunc('month', rr.shipped_at at time zone 'Asia/Bangkok') = v_month
    )::integer
  from public.reward_redemptions rr
  where rr.fulfillment_status is not null
    and rr.status <> 'cancelled';
end;
$fn$;

revoke all on function public.admin_reward_fulfillment_stats() from public, anon;
grant execute on function public.admin_reward_fulfillment_stats() to authenticated, service_role;


-- ============================================================
-- 7. คิวจัดส่ง (แอดมิน) — เพิ่มคอลัมน์ใหม่
-- ============================================================
drop view if exists public.admin_reward_requests;

create view public.admin_reward_requests as
select
  rr.id,
  rr.user_id,
  rr.reward_id,
  rr.redemption_code,
  rr.points_used,
  rr.status,
  rr.fulfillment_status,
  rr.option_label,
  rr.recipient_name,
  rr.shipping_phone,
  rr.shipping_address,
  rr.tracking_number,
  rr.shipping_carrier,
  rr.shipping_note,
  rr.shipped_at,
  rr.delivered_at,
  rr.received_at,
  rr.cancel_reason,
  rr.created_at,
  rr.expires_at,
  rr.used_at,
  r.name      as reward_name,
  r.category  as reward_category,
  r.image_url as reward_image,
  p.username,
  p.full_name,
  p.avatar_url,
  p.phone
from public.reward_redemptions rr
join public.rewards  r on r.id = rr.reward_id
join public.profiles p on p.id = rr.user_id
where rr.fulfillment_status is not null
  and public.is_admin();

grant select on public.admin_reward_requests to authenticated;


-- ============================================================
-- 8. ประวัติการแลกรางวัลทั้งหมด (แอดมิน)
-- ============================================================
-- ต่างจาก admin_reward_requests ตรงที่ "ไม่กรอง" — รวมคูปองส่วนลดที่ไม่ต้อง
-- ส่งของด้วย เพราะคำถามที่หน้านี้ต้องตอบคือ "ใครแลกอะไรไปบ้าง" ไม่ใช่
-- "เหลืออะไรต้องส่ง"
--
-- usage_state คำนวณด้วยสูตรเดียวกับ redemptionState() ฝั่งหน้าเว็บ (0047) —
-- "หมดอายุ" ไม่ใช่ค่าที่เก็บไว้ในตาราง จึงต้องคิดสด ๆ ทุกครั้งที่อ่าน
--
-- security definer view (ไม่ใส่ security_invoker) เหมือน admin_reward_requests
-- เพราะต้องอ่านชื่อ/เบอร์ของลูกค้าคนอื่นซึ่ง profiles_select_own ปิดไว้ —
-- is_admin() ใน where เป็นตัวกั้นเอง

create or replace view public.admin_redemption_history as
select
  rr.id,
  rr.user_id,
  rr.reward_id,
  rr.redemption_code,
  rr.points_used,
  rr.status,
  rr.fulfillment_status,
  rr.option_label,
  rr.recipient_name,
  rr.shipping_phone,
  rr.shipping_address,
  rr.tracking_number,
  rr.shipping_carrier,
  rr.shipped_at,
  rr.delivered_at,
  rr.received_at,
  rr.used_at,
  rr.used_note,
  rr.cancel_reason,
  rr.expires_at,
  rr.created_at,
  case
    when rr.status = 'cancelled' then 'cancelled'
    when rr.status = 'completed' then 'used'
    when rr.expires_at is not null and rr.expires_at < now() then 'expired'
    else 'unused'
  end as usage_state,
  r.name      as reward_name,
  r.category  as reward_category,
  r.image_url as reward_image,
  r.benefit_type,
  r.requires_shipping,
  p.username,
  p.full_name,
  p.avatar_url,
  p.phone
from public.reward_redemptions rr
join public.rewards  r on r.id = rr.reward_id
join public.profiles p on p.id = rr.user_id
where public.is_admin();

grant select on public.admin_redemption_history to authenticated;


-- ============================================================
-- 9. ตัวเลขสรุปของหน้าประวัติการแลก (แอดมิน)
-- ============================================================
-- ตอบสามคำถามที่โจทย์ถามตรง ๆ: แลกไปทั้งหมดกี่ใบ ใช้ไปแล้วกี่ใบ และแลกแล้ว
-- ยังไม่ได้ใช้กี่ใบ — บวกยอดแต้มที่ถูกใช้ไปกับจำนวนคนที่แลก ซึ่งเป็นสองตัวที่
-- ใช้ประเมินว่าโปรแกรมแต้มคุ้มไหม

create or replace function public.admin_redemption_stats()
returns table (
  total_count      integer,
  used_count       integer,
  unused_count     integer,
  expired_count    integer,
  cancelled_count  integer,
  shipping_count   integer,
  awaiting_receipt integer,
  points_spent     integer,
  member_count     integer
)
language plpgsql
security definer
set search_path = public
as $fn$
begin
  if not public.is_admin() then
    raise exception 'ต้องเป็นผู้ดูแลระบบเท่านั้น';
  end if;

  return query
  select
    count(*)::integer,
    count(*) filter (where rr.status = 'completed')::integer,
    count(*) filter (
      where rr.status = 'pending'
        and (rr.expires_at is null or rr.expires_at >= now())
    )::integer,
    count(*) filter (
      where rr.status = 'pending'
        and rr.expires_at is not null
        and rr.expires_at < now()
    )::integer,
    count(*) filter (where rr.status = 'cancelled')::integer,
    count(*) filter (
      where rr.status <> 'cancelled'
        and rr.fulfillment_status is not null
        and rr.fulfillment_status <> 'received'
    )::integer,
    count(*) filter (
      where rr.status <> 'cancelled'
        and rr.fulfillment_status in ('delivered', 'pickup')
    )::integer,
    coalesce(sum(rr.points_used) filter (where rr.status <> 'cancelled'), 0)::integer,
    count(distinct rr.user_id)::integer
  from public.reward_redemptions rr;
end;
$fn$;

revoke all on function public.admin_redemption_stats() from public, anon;
grant execute on function public.admin_redemption_stats() to authenticated, service_role;


-- ============================================================
-- 10. สิทธิ์จองล่วงหน้า — ทำให้รางวัลใบนี้มีผลจริง
-- ============================================================
-- ก่อนหน้านี้ระบบไม่เคยจำกัดวันจองล่วงหน้าเลยสักชั้น: ตาราง bookings มีแค่
-- trigger กันวันย้อนหลัง (0005) ส่วนเพดาน 62 วันที่ผู้ใช้เห็นเป็นแค่ max ของ
-- ช่อง input type=date กับช่วงที่ facility_day_availability ยอมตอบ —
-- ยิง create_booking ตรง ๆ ด้วยสล็อตของปีหน้าก็ผ่าน
--
-- ตั้งเพดานจริงที่ 30 วันสำหรับทุกคน (แอดมินแก้ได้) แล้วให้รางวัลใบนี้ต่อ
-- ให้อีกตามจำนวนวันใน benefit_value — สิทธิ์ที่ขาย 3,000 แต้มจึงให้อะไรที่
-- คนอื่นไม่มีจริง ๆ

alter table public.reward_settings
  add column if not exists advance_booking_days integer not null default 30;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'reward_settings_advance_days_check'
  ) then
    alter table public.reward_settings
      add constraint reward_settings_advance_days_check
      check (advance_booking_days between 1 and 365);
  end if;
end;
$$;

-- ผูกสิทธิประโยชน์ให้รางวัลที่ seed ไว้ใน 0047 — ครั้งเดียวตอนอัปเกรด
-- จากนั้นแอดมินแก้เองได้จากหน้าจัดการรางวัล
update public.rewards
set benefit_type  = 'advance_booking',
    benefit_value = 30,
    description   = 'จองสนามล่วงหน้าได้ไกลกว่าปกติอีก 30 วัน มีผลทันทีที่แลก',
    terms         = 'สิทธิ์มีผล 30 วันนับจากวันที่แลก ใช้ได้กับทุกสนามในเครือ ไม่สามารถโอนสิทธิ์ให้ผู้อื่นได้'
where name = 'สิทธิ์จองล่วงหน้า 30 วัน'
  and benefit_type = 'none';

-- สิทธิ์แบบนี้ไม่ใช่คูปองที่ต้องเอาไปยื่นตอนจอง — มันมีผลกับบัญชีทันทีที่แลก
-- จึงปิดใบเป็น completed ตั้งแต่วินาทีแรก ไม่งั้นจะค้างเป็น "ยังไม่ได้ใช้" อยู่
-- 30 วันทั้งที่ใช้อยู่ตลอดเวลา และจะไปโผล่ใน usable_coupons ให้กดใช้ลดราคา
-- ตอนจ่ายเงินทั้งที่ลดอะไรไม่ได้
--
-- ทำเป็น trigger แทนการแก้ redeem_reward() เพราะฟังก์ชันนั้นยาวและถูกเขียนทับ
-- มาแล้วสองรอบ (0047 -> 0049) การแตะซ้ำมีโอกาสทำของเดิมหายมากกว่าที่ควร
create or replace function public.activate_privilege_redemption()
returns trigger
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_benefit public.reward_benefit_type;
begin
  select benefit_type into v_benefit
  from public.rewards where id = new.reward_id;

  if v_benefit = 'advance_booking' then
    update public.reward_redemptions
    set status    = 'completed',
        used_at   = coalesce(used_at, now()),
        used_note = coalesce(
          used_note,
          format('สิทธิ์จองล่วงหน้ามีผลทันที ถึงวันที่ %s',
                 to_char(new.expires_at at time zone 'Asia/Bangkok', 'DD/MM/YYYY'))
        )
    where id = new.id;
  end if;

  return null;
end;
$fn$;

drop trigger if exists activate_privilege_redemption on public.reward_redemptions;
create trigger activate_privilege_redemption
after insert on public.reward_redemptions
for each row execute function public.activate_privilege_redemption();


-- คูปองที่เอาไปลดค่าสนามได้ — ต้องไม่รวมสิทธิ์จองล่วงหน้า (status = completed
-- กรองออกให้อยู่แล้ว แต่เขียนไว้ตรง ๆ ด้วย เผื่อวันหนึ่งเงื่อนไขสถานะเปลี่ยน)
create or replace view public.usable_coupons
with (security_invoker = on) as
select
  rr.id,
  rr.user_id,
  rr.redemption_code,
  rr.expires_at,
  rr.created_at,
  r.name     as reward_name,
  r.category as reward_category,
  r.benefit_type,
  r.benefit_value
from public.reward_redemptions rr
join public.rewards r on r.id = rr.reward_id
where rr.status = 'pending'
  and r.benefit_type not in ('none', 'advance_booking')
  and (rr.expires_at is null or rr.expires_at > now())
  and not exists (
    select 1 from public.bookings b
    where b.redemption_id = rr.id
      and b.status in ('pending', 'confirmed', 'completed')
  );

revoke all on public.usable_coupons from anon, authenticated;
grant select on public.usable_coupons to authenticated;


-- ============================================================
-- 11. จองล่วงหน้าได้กี่วัน
-- ============================================================
-- _booking_window_days เป็นตัวที่ create_booking ใช้ตัดสินจริง (ไม่ grant ให้
-- ใครเรียกตรง) ส่วน my_booking_window() เป็นตัวที่หน้าเว็บถามเพื่อเซ็ต max ของ
-- ช่องเลือกวันที่ให้ตรงกัน — สองตัวอ่านสูตรเดียวกัน หน้าเว็บจึงไม่มีทางโชว์
-- วันที่ที่ backend จะปฏิเสธ
--
-- นับสิทธิ์ที่ยังไม่หมดอายุด้วย max() ไม่ใช่ sum() — แลกสิทธิ์เดิมซ้ำสองใบ
-- ไม่ได้แปลว่าจองไกลขึ้นเป็นสองเท่า

create or replace function public._booking_window_days(p_user uuid)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select advance_booking_days from public.reward_settings where id = 1),
    30
  ) + coalesce(
    (select max(r.benefit_value)::int
       from public.reward_redemptions rr
       join public.rewards r on r.id = rr.reward_id
      where rr.user_id = p_user
        and r.benefit_type = 'advance_booking'
        and rr.status <> 'cancelled'
        and (rr.expires_at is null or rr.expires_at > now())),
    0
  );
$$;

revoke all on function public._booking_window_days(uuid) from public, anon, authenticated;


create or replace function public.my_booking_window()
returns table (
  base_days   integer,
  bonus_days  integer,
  total_days  integer,
  last_date   date,
  bonus_until timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    v.base,
    v.bonus,
    v.base + v.bonus,
    ((now() at time zone 'Asia/Bangkok')::date + (v.base + v.bonus)),
    v.until
  from (
    select
      coalesce((select advance_booking_days from public.reward_settings where id = 1), 30) as base,
      coalesce((select max(r.benefit_value)::int
                  from public.reward_redemptions rr
                  join public.rewards r on r.id = rr.reward_id
                 where rr.user_id = (select auth.uid())
                   and r.benefit_type = 'advance_booking'
                   and rr.status <> 'cancelled'
                   and (rr.expires_at is null or rr.expires_at > now())), 0) as bonus,
      (select max(rr.expires_at)
         from public.reward_redemptions rr
         join public.rewards r on r.id = rr.reward_id
        where rr.user_id = (select auth.uid())
          and r.benefit_type = 'advance_booking'
          and rr.status <> 'cancelled'
          and (rr.expires_at is null or rr.expires_at > now())) as until
  ) v;
$$;

revoke all on function public.my_booking_window() from public, anon;
grant execute on function public.my_booking_window() to authenticated;
